modLoader="javafml"
loaderVersion="[51,)"
issueTrackerURL="https://github.com/North-West-Wind/forge-autofish/issues"
license="GPL v3"

[[mods]]
modId="forgeautofish"
version="7.1.0"
displayName="AutoFish for Forge"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/forge-autofish/master/update.json"
displayURL="https://github.com/North-West-Wind/forge-autofish/"
logoFile="forgeautofish.png"
credits="Thank you for using this mod"
authors="NorthWestWind"
description='''
I like playing survival, but fishing is a boring activity...
Therefore, I made this mod!
Now you can AFK Fish like no one else!

Note that this is my first mod, so there might be bugs.
'''

[[dependencies.forgeautofish]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.forgeautofish]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
